# Generated by Django 3.2.6 on 2021-08-24 06:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('img', models.ImageField(upload_to='', verbose_name='путь к картинке')),
                ('slug', models.SlugField(max_length=100)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', related_query_name='child', to='category.category', verbose_name='родительская категория')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ['tree_id', 'lft'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='название товара')),
                ('description', models.TextField(max_length=255, verbose_name='описание')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='цена')),
                ('available', models.BooleanField(default=True, verbose_name='Доступен')),
                ('available_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Доступное количество')),
                ('slug', models.SlugField(max_length=140)),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Рейтинг')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', related_query_name='product', to='category.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
                'ordering': ['-price'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.ImageField(upload_to='', verbose_name='путь')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='category.product', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'картинка товара',
                'verbose_name_plural': 'картинки товаров',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='процент скидки')),
                ('start_datetime', models.DateTimeField(verbose_name='время начала скидки')),
                ('end_datetime', models.DateTimeField(verbose_name='время конца скидки')),
                ('products', models.ManyToManyField(related_name='discounts', related_query_name='discount', to='category.Product', verbose_name='скидка')),
            ],
            options={
                'verbose_name': 'скидка',
                'verbose_name_plural': 'скидки',
                'ordering': ['percent'],
            },
        ),
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='характеристика')),
                ('value', models.CharField(max_length=100, verbose_name='значение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', related_query_name='characteristic', to='category.product', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'характеристика',
                'verbose_name_plural': 'характеристик',
                'ordering': ['name'],
            },
        ),
    ]
